name: build and test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install node_modules
        run: npm install
      - name: Build production bundle
        run: npm run build:prod
      - name: Run linting for typescript
        run: npm run lint:ts
      - name: Run linting for scss
        run: npm run lint:scss
      - name: Run unit testing
        run: npm run test:unit